### PR TITLE
use newer global package install arguments

### PR DESCRIPTION
**Pull request by ghost**
starting in npm 8.11.0, the `-g` flag is deprecated and `--location=global` is used instead.
this pull request adds this change within the initialization of a new pylon project using the cli.

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
starting in npm 8.11.0, the -g flag is deprecated and --location=global is used instead.
this pull request adds this change within the initialization of a new pylon project using the cli.
**this might cause an issue with users using older versions of npm, unsure as not tested.**

**Comment by liamhtml** [comment]
I looked into this and it appears to be a [mistake](https://github.com/npm/statusboard/issues/518) that npm undid. updating npm should fix this.

**Comment by ghost** [comment]
i updated my npm to 8.14.0 and i still get the deprecation notice, somethings going on here

**Comment by liamhtml** [comment]
I'm not really sure what to tell you then, maybe check out [this comment on that issue.](https://github.com/npm/statusboard/issues/518#issuecomment-1156647541)

**Pull request closed without merging**
